/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_app_rzm_utils_BsUpdateUtils */

#ifndef _Included_com_app_rzm_utils_BsUpdateUtils
#define _Included_com_app_rzm_utils_BsUpdateUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_app_rzm_utils_BsUpdateUtils
 * Method:    combine
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_app_rzm_utils_BsUpdateUtils_combine
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_app_rzm_utils_BsUpdateUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_app_rzm_utils_BsUpdateUtils_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
