/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <libavcodec/avcodec.h>
#include "../queue.h"
/* Header for class com_example_ndk_ffmpeg_FFmpegUtils */

#ifndef _Included_com_example_ndk_ffmpeg_FFmpegUtils
#define _Included_com_example_ndk_ffmpeg_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_example_ndk_ffmpeg_FFmpegUtils
 * Method:    render
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_app_rzm_utils_FFmpegUtils_play
  (JNIEnv *, jobject, jstring, jobject);


#ifdef __cplusplus
}
#endif
#endif
